[2024-10-10T15:08:29.581+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_C.task_0_S3_to_S3 manual__2024-10-10T14:55:53.958876+00:00 [queued]>
[2024-10-10T15:08:29.585+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_C.task_0_S3_to_S3 manual__2024-10-10T14:55:53.958876+00:00 [queued]>
[2024-10-10T15:08:29.585+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-10T15:08:29.585+0000] {taskinstance.py:1289} INFO - Starting attempt 5 of 5
[2024-10-10T15:08:29.586+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-10T15:08:29.590+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): task_0_S3_to_S3> on 2024-10-10 14:55:53.958876+00:00
[2024-10-10T15:08:29.599+0000] {standard_task_runner.py:55} INFO - Started process 13515 to run task
[2024-10-10T15:08:29.601+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_C', 'task_0_S3_to_S3', 'manual__2024-10-10T14:55:53.958876+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_C.py', '--cfg-path', '/tmp/tmpg04xot15']
[2024-10-10T15:08:29.603+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask task_0_S3_to_S3
[2024-10-10T15:08:29.625+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-10T15:08:29.667+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_C.task_0_S3_to_S3 manual__2024-10-10T14:55:53.958876+00:00 [running]> on host 1f7125be5d21
[2024-10-10T15:08:29.705+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_C
AIRFLOW_CTX_TASK_ID=task_0_S3_to_S3
AIRFLOW_CTX_EXECUTION_DATE=2024-10-10T14:55:53.958876+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-10T14:55:53.958876+00:00
[2024-10-10T15:08:29.805+0000] {s3_s3.py:42} INFO - Executing File pattern check......
[2024-10-10T15:08:29.805+0000] {logging_mixin.py:137} INFO - source_s3_path : s3://sdevalla-buck/test/target/reddit_target_yyyymmdd.csv
[2024-10-10T15:08:29.805+0000] {logging_mixin.py:137} INFO - bn: sdevalla-buck
[2024-10-10T15:08:29.805+0000] {logging_mixin.py:137} INFO - prefix: test/target
[2024-10-10T15:08:30.337+0000] {logging_mixin.py:137} INFO - objs list:  ['test/target/reddit_target_20241010.csv']
[2024-10-10T15:08:30.338+0000] {logging_mixin.py:137} INFO - obj req: ['reddit_target_20241010.csv']
[2024-10-10T15:08:30.339+0000] {logging_mixin.py:137} INFO - match list:  ['reddit_target_20241010.csv']
[2024-10-10T15:08:30.340+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/s3_s3.py", line 283, in main_s3_s3
    result = s3_s3_copy(ss3_conn, ts3_conn, source_s3_file, target_s3_file)
  File "/opt/airflow/scripts/s3_s3.py", line 147, in s3_s3_copy
    latest_file = file_pattern_check(source_s3_file,ss3_conn)
  File "/opt/airflow/scripts/s3_s3.py", line 96, in file_pattern_check
    latest_file = max(match_list)
  File "/usr/local/lib/python3.9/site-packages/pyspark/sql/utils.py", line 160, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyspark/sql/functions.py", line 452, in max
    return _invoke_function_over_columns("max", col)
  File "/usr/local/lib/python3.9/site-packages/pyspark/sql/functions.py", line 103, in _invoke_function_over_columns
    return _invoke_function(name, *(_to_java_column(col) for col in cols))
  File "/usr/local/lib/python3.9/site-packages/pyspark/sql/functions.py", line 103, in <genexpr>
    return _invoke_function(name, *(_to_java_column(col) for col in cols))
  File "/usr/local/lib/python3.9/site-packages/pyspark/sql/column.py", line 65, in _to_java_column
    raise TypeError(
TypeError: Invalid argument, not a string or column: ['reddit_target_20241010.csv'] of type <class 'list'>. For column literals, use 'lit', 'array', 'struct' or 'create_map' function.
[2024-10-10T15:08:30.359+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pipeline_C, task_id=task_0_S3_to_S3, execution_date=20241010T145553, start_date=20241010T150829, end_date=20241010T150830
[2024-10-10T15:08:30.370+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 10 for task task_0_S3_to_S3 (Invalid argument, not a string or column: ['reddit_target_20241010.csv'] of type <class 'list'>. For column literals, use 'lit', 'array', 'struct' or 'create_map' function.; 13515)
[2024-10-10T15:08:30.393+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-10-10T15:08:30.410+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
