[2024-10-09T22:34:55.258+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_A.task_0_S3_to_DB manual__2024-10-09T22:24:56.777422+00:00 [queued]>
[2024-10-09T22:34:55.262+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_A.task_0_S3_to_DB manual__2024-10-09T22:24:56.777422+00:00 [queued]>
[2024-10-09T22:34:55.262+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-09T22:34:55.262+0000] {taskinstance.py:1289} INFO - Starting attempt 3 of 3
[2024-10-09T22:34:55.262+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-09T22:34:55.267+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): task_0_S3_to_DB> on 2024-10-09 22:24:56.777422+00:00
[2024-10-09T22:34:55.274+0000] {standard_task_runner.py:55} INFO - Started process 5572 to run task
[2024-10-09T22:34:55.276+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_A', 'task_0_S3_to_DB', 'manual__2024-10-09T22:24:56.777422+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_A.py', '--cfg-path', '/tmp/tmppvpi30ru']
[2024-10-09T22:34:55.277+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask task_0_S3_to_DB
[2024-10-09T22:34:55.300+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-09T22:34:55.385+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_A.task_0_S3_to_DB manual__2024-10-09T22:24:56.777422+00:00 [running]> on host 63edb90a1db5
[2024-10-09T22:34:55.471+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_A
AIRFLOW_CTX_TASK_ID=task_0_S3_to_DB
AIRFLOW_CTX_EXECUTION_DATE=2024-10-09T22:24:56.777422+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-09T22:24:56.777422+00:00
[2024-10-09T22:34:55.472+0000] {s3_db.py:102} INFO - Executing S3 File read.......
[2024-10-09T22:34:55.472+0000] {s3_db.py:18} INFO - Creating Spark session ......
[2024-10-09T22:35:08.856+0000] {s3_db.py:211} INFO - Executing file writing function .....
[2024-10-09T22:35:08.859+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/s3_db.py", line 284, in main_s3_db
    result = db_file_write(db_conn, target_db, target_table, inputs[0],load_type)
  File "/opt/airflow/scripts/s3_db.py", line 213, in db_file_write
    db_name = target_table.split('.')[0]
AttributeError: 'NoneType' object has no attribute 'split'
[2024-10-09T22:35:08.883+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pipeline_A, task_id=task_0_S3_to_DB, execution_date=20241009T222456, start_date=20241009T223455, end_date=20241009T223508
[2024-10-09T22:35:08.897+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 5 for task task_0_S3_to_DB ('NoneType' object has no attribute 'split'; 5572)
[2024-10-09T22:35:08.936+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-10-09T22:35:08.981+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
