[2024-10-10T21:16:57.686+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_A.task_0_S3_to_DB manual__2024-10-10T21:16:54.314271+00:00 [queued]>
[2024-10-10T21:16:57.691+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_A.task_0_S3_to_DB manual__2024-10-10T21:16:54.314271+00:00 [queued]>
[2024-10-10T21:16:57.691+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-10T21:16:57.692+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-10-10T21:16:57.692+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-10T21:16:57.697+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): task_0_S3_to_DB> on 2024-10-10 21:16:54.314271+00:00
[2024-10-10T21:16:57.704+0000] {standard_task_runner.py:55} INFO - Started process 87465 to run task
[2024-10-10T21:16:57.708+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_A', 'task_0_S3_to_DB', 'manual__2024-10-10T21:16:54.314271+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_A.py', '--cfg-path', '/tmp/tmpdxrtorj6']
[2024-10-10T21:16:57.723+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask task_0_S3_to_DB
[2024-10-10T21:16:57.789+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-10T21:16:57.864+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_A.task_0_S3_to_DB manual__2024-10-10T21:16:54.314271+00:00 [running]> on host d6685a94b59c
[2024-10-10T21:16:57.897+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_A
AIRFLOW_CTX_TASK_ID=task_0_S3_to_DB
AIRFLOW_CTX_EXECUTION_DATE=2024-10-10T21:16:54.314271+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-10T21:16:54.314271+00:00
[2024-10-10T21:16:57.902+0000] {s3_db.py:130} INFO - Executing S3 File read.......
[2024-10-10T21:16:57.902+0000] {s3_db.py:17} INFO - Creating Spark session ......
[2024-10-10T21:17:12.664+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/s3_db.py", line 305, in main_s3_db
    inputs = s3_file_read(s3_conn, source_s3_path, header, delimiter, s3_access, db_access,target_table)
  File "/opt/airflow/scripts/s3_db.py", line 190, in s3_file_read
    run_logger('S3-DB','insert', s3_access,source_s3_path, file_name, 'read',rc, db_access, target_table, 'success')
TypeError: run_logger() missing 1 required positional argument: 'status'
[2024-10-10T21:17:12.709+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pipeline_A, task_id=task_0_S3_to_DB, execution_date=20241010T211654, start_date=20241010T211657, end_date=20241010T211712
[2024-10-10T21:17:12.730+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 18 for task task_0_S3_to_DB (run_logger() missing 1 required positional argument: 'status'; 87465)
[2024-10-10T21:17:12.753+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-10-10T21:17:12.837+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
