[2024-10-10T20:01:58.270+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_A.task_0_S3_to_DB manual__2024-10-10T19:57:19.378386+00:00 [queued]>
[2024-10-10T20:01:58.275+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_A.task_0_S3_to_DB manual__2024-10-10T19:57:19.378386+00:00 [queued]>
[2024-10-10T20:01:58.276+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-10T20:01:58.276+0000] {taskinstance.py:1289} INFO - Starting attempt 4 of 4
[2024-10-10T20:01:58.276+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-10T20:01:58.282+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): task_0_S3_to_DB> on 2024-10-10 19:57:19.378386+00:00
[2024-10-10T20:01:58.292+0000] {standard_task_runner.py:55} INFO - Started process 52360 to run task
[2024-10-10T20:01:58.295+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_A', 'task_0_S3_to_DB', 'manual__2024-10-10T19:57:19.378386+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_A.py', '--cfg-path', '/tmp/tmpqht79to7']
[2024-10-10T20:01:58.296+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask task_0_S3_to_DB
[2024-10-10T20:01:58.375+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-10T20:01:58.797+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_A.task_0_S3_to_DB manual__2024-10-10T19:57:19.378386+00:00 [running]> on host d6685a94b59c
[2024-10-10T20:01:58.903+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_A
AIRFLOW_CTX_TASK_ID=task_0_S3_to_DB
AIRFLOW_CTX_EXECUTION_DATE=2024-10-10T19:57:19.378386+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-10T19:57:19.378386+00:00
[2024-10-10T20:01:58.919+0000] {run_logger.py:23} INFO - Updating run log for  operation....
[2024-10-10T20:01:58.919+0000] {run_logger.py:31} INFO - Error: syntax error at or near "TABLE"
LINE 1: INSERT INTO TABLE pipeline_run_log VALUES('S3-DB','A','s3_ac...
                    ^

[2024-10-10T20:01:58.920+0000] {s3_db.py:101} INFO - Executing S3 File read.......
[2024-10-10T20:01:58.920+0000] {s3_db.py:17} INFO - Creating Spark session ......
[2024-10-10T20:02:10.204+0000] {s3_db.py:210} INFO - Executing file writing function .....
[2024-10-10T20:02:10.959+0000] {s3_db.py:235} INFO - Completed writing to target table.......
[2024-10-10T20:02:10.960+0000] {s3_db.py:286} INFO - Updating run_log, marking status as success........ 
[2024-10-10T20:02:10.960+0000] {s3_db.py:288} INFO - 918 records transferred from s3a://sdevalla-buck/test/sftp_20240323.txt to ***.reddit_d
[2024-10-10T20:02:11.370+0000] {python.py:177} INFO - Done. Returned value was: 918
[2024-10-10T20:02:11.440+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=pipeline_A, task_id=task_0_S3_to_DB, execution_date=20241010T195719, start_date=20241010T200158, end_date=20241010T200211
[2024-10-10T20:02:11.510+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-10-10T20:02:11.588+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
