[2024-10-10T20:05:20.437+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_A.task_0_S3_to_DB manual__2024-10-10T19:57:19.378386+00:00 [queued]>
[2024-10-10T20:05:20.444+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_A.task_0_S3_to_DB manual__2024-10-10T19:57:19.378386+00:00 [queued]>
[2024-10-10T20:05:20.444+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-10T20:05:20.444+0000] {taskinstance.py:1289} INFO - Starting attempt 5 of 5
[2024-10-10T20:05:20.444+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-10T20:05:20.451+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): task_0_S3_to_DB> on 2024-10-10 19:57:19.378386+00:00
[2024-10-10T20:05:20.477+0000] {standard_task_runner.py:55} INFO - Started process 54170 to run task
[2024-10-10T20:05:20.502+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_A', 'task_0_S3_to_DB', 'manual__2024-10-10T19:57:19.378386+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_A.py', '--cfg-path', '/tmp/tmpjdn4_n2r']
[2024-10-10T20:05:20.510+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask task_0_S3_to_DB
[2024-10-10T20:05:20.584+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-10T20:05:20.812+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_A.task_0_S3_to_DB manual__2024-10-10T19:57:19.378386+00:00 [running]> on host d6685a94b59c
[2024-10-10T20:05:20.900+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_A
AIRFLOW_CTX_TASK_ID=task_0_S3_to_DB
AIRFLOW_CTX_EXECUTION_DATE=2024-10-10T19:57:19.378386+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-10T19:57:19.378386+00:00
[2024-10-10T20:05:20.913+0000] {run_logger.py:23} INFO - Updating run log for  operation....
[2024-10-10T20:05:20.914+0000] {run_logger.py:31} INFO - Error: syntax error at or near ","
LINE 1: ...s3a://sdevalla-buck/test/sftp_20240323.txt','','',,'pdb','ai...
                                                             ^

[2024-10-10T20:05:20.914+0000] {s3_db.py:101} INFO - Executing S3 File read.......
[2024-10-10T20:05:20.914+0000] {s3_db.py:17} INFO - Creating Spark session ......
[2024-10-10T20:05:31.595+0000] {s3_db.py:210} INFO - Executing file writing function .....
[2024-10-10T20:05:32.070+0000] {s3_db.py:235} INFO - Completed writing to target table.......
[2024-10-10T20:05:32.070+0000] {s3_db.py:286} INFO - Updating run_log, marking status as success........ 
[2024-10-10T20:05:32.070+0000] {s3_db.py:288} INFO - 918 records transferred from s3a://sdevalla-buck/test/sftp_20240323.txt to ***.reddit_d
[2024-10-10T20:05:32.291+0000] {python.py:177} INFO - Done. Returned value was: 918
[2024-10-10T20:05:32.365+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=pipeline_A, task_id=task_0_S3_to_DB, execution_date=20241010T195719, start_date=20241010T200520, end_date=20241010T200532
[2024-10-10T20:05:32.419+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2024-10-10T20:05:32.467+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
