[2024-10-10T03:37:25.703+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_B.task_0_DB_to_S3 manual__2024-10-10T03:37:22.574622+00:00 [queued]>
[2024-10-10T03:37:25.722+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_B.task_0_DB_to_S3 manual__2024-10-10T03:37:22.574622+00:00 [queued]>
[2024-10-10T03:37:25.723+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2024-10-10T03:37:25.723+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2024-10-10T03:37:25.723+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2024-10-10T03:37:25.737+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): task_0_DB_to_S3> on 2024-10-10 03:37:22.574622+00:00
[2024-10-10T03:37:25.743+0000] {standard_task_runner.py:55} INFO - Started process 68579 to run task
[2024-10-10T03:37:25.745+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'pipeline_B', 'task_0_DB_to_S3', 'manual__2024-10-10T03:37:22.574622+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_B.py', '--cfg-path', '/tmp/tmpni5n80cl']
[2024-10-10T03:37:25.747+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask task_0_DB_to_S3
[2024-10-10T03:37:25.760+0000] {logging_mixin.py:137} WARNING - /usr/local/lib/python3.9/site-packages/***/settings.py:250 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-10T03:37:25.788+0000] {task_command.py:389} INFO - Running <TaskInstance: pipeline_B.task_0_DB_to_S3 manual__2024-10-10T03:37:22.574622+00:00 [running]> on host d7e677fa2cf4
[2024-10-10T03:37:25.836+0000] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=pipeline_B
AIRFLOW_CTX_TASK_ID=task_0_DB_to_S3
AIRFLOW_CTX_EXECUTION_DATE=2024-10-10T03:37:22.574622+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-10T03:37:22.574622+00:00
[2024-10-10T03:37:25.840+0000] {db_s3.py:17} INFO - Creating Spark session ......
[2024-10-10T03:37:25.840+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/scripts/db_s3.py", line 255, in main_db_s3
    inputs = table_data_read(s3_conn, db_conn, source_db, source_table, DML)
  File "/opt/airflow/scripts/db_s3.py", line 41, in table_data_read
    create_spark_session(s3_conn)
  File "/opt/airflow/scripts/db_s3.py", line 20, in create_spark_session
    spark = SparkSession.builder \
NameError: name 'SparkSession' is not defined
[2024-10-10T03:37:25.845+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=pipeline_B, task_id=task_0_DB_to_S3, execution_date=20241010T033722, start_date=20241010T033725, end_date=20241010T033725
[2024-10-10T03:37:25.853+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 18 for task task_0_DB_to_S3 (name 'SparkSession' is not defined; 68579)
[2024-10-10T03:37:25.886+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2024-10-10T03:37:25.896+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
